import { useEffect, useMemo, useRef, useState } from 'react';
import { Plus, X, Music, GraduationCap, Users, MoreHorizontal, Settings, Car, Utensils, Home, Megaphone, Trash2, ArrowUpRight, ArrowDownRight, Mic, Camera, Download, Upload, Search, BarChart3 } from 'lucide-react';

const IN=[{key:'cache',label:'Cachê / Show',icon:Music},{key:'mentoria',label:'Mentoria',icon:GraduationCap},{key:'parceria',label:'Parceria',icon:Users},{key:'outros_e',label:'Outros',icon:MoreHorizontal}];
const OUT=[{key:'equipamento',label:'Equipamento',icon:Settings},{key:'transporte',label:'Transporte',icon:Car},{key:'alimentacao',label:'Alimentação',icon:Utensils},{key:'estudio',label:'Estúdio / Aluguel',icon:Home},{key:'marketing',label:'Marketing',icon:Megaphone},{key:'outros_s',label:'Outros',icon:MoreHorizontal}];
const C={bg:'#14171A',surface:'#1C2024',alt:'#22262B',border:'#2C3136',gold:'#C9A24B',red:'#C1503D',text:'#F1EDE5',muted:'#8F969C',faint:'#5C6268'};
const brl=n=>(Number(n)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function today(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function cat(k){return [...IN,...OUT].find(x=>x.key===k)||OUT[5]}
function inferVoice(text){const s=text.toLowerCase();const nums=s.match(/\d+(?:[.,]\d+)?/g)||[];const amount=nums.length?nums.map(x=>Number(x.replace(',','.'))).sort((a,b)=>b-a)[0]:'';let type=/recebi|entrou|entrada|cach[eê]|show|mentoria|parceria/.test(s)?'entrada':'saida';let category=type==='entrada'?'outros_e':'outros_s';if(/cach[eê]|show/.test(s))category='cache';else if(/mentoria/.test(s))category='mentoria';else if(/parceria/.test(s))category='parceria';else if(/uber|99|gasolina|combust|ped[aá]gio|transporte|t[aá]xi/.test(s))category='transporte';else if(/almo[cç]|jantar|comida|restaurante|lanche|aliment/.test(s))category='alimentacao';else if(/est[uú]dio|aluguel/.test(s))category='estudio';else if(/marketing|an[uú]ncio|tr[aá]fego|instagram/.test(s))category='marketing';else if(/equipamento|fone|microfone|cabo|controladora/.test(s))category='equipamento';return{type,amount,category,note:text,date:today()}}

export default function App(){
 const [tx,setTx]=useState(()=>{try{return JSON.parse(localStorage.getItem('dcross.transactions')||'[]')}catch{return []}}),[filter,setFilter]=useState('all'),[open,setOpen]=useState(false),[type,setType]=useState('entrada'),[amount,setAmount]=useState(''),[category,setCategory]=useState('cache'),[note,setNote]=useState(''),[date,setDate]=useState(today()),[del,setDel]=useState(null),[search,setSearch]=useState(''),[listening,setListening]=useState(false),[message,setMessage]=useState('');
 const importRef=useRef(null),receiptRef=useRef(null),recRef=useRef(null);
 useEffect(()=>localStorage.setItem('dcross.transactions',JSON.stringify(tx)),[tx]);
 const data=useMemo(()=>{let saldo=0,ins=0,outs=0;const now=new Date();tx.forEach(t=>{saldo+=t.type==='entrada'?t.amount:-t.amount;const d=new Date(t.date+'T00:00:00');if(d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear())t.type==='entrada'?ins+=t.amount:outs+=t.amount});const q=search.toLowerCase();const list=tx.filter(t=>(filter==='all'||(filter==='in'?t.type==='entrada':t.type==='saida'))&&(!q||`${cat(t.category).label} ${t.note||''}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt);return{saldo,ins,outs,list}},[tx,filter,search]);
 function reset(){setType('entrada');setAmount('');setCategory('cache');setNote('');setDate(today());setMessage('')}
 function save(){const a=parseFloat(String(amount).replace(',','.'));if(!(a>0))return;setTx([{id:crypto.randomUUID?.()||String(Date.now()),type,amount:a,category,note:note.trim(),date,createdAt:Date.now()},...tx]);reset();setOpen(false)}
 function voice(){setOpen(true);setMessage('');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMessage('Voz não suportada neste navegador. Use Chrome/Android ou preencha manualmente.');return}const r=new SR();recRef.current=r;r.lang='pt-BR';r.interimResults=false;r.onstart=()=>setListening(true);r.onerror=()=>{setListening(false);setMessage('Não consegui acessar/entender o microfone.');};r.onend=()=>setListening(false);r.onresult=e=>{const p=inferVoice(e.results[0][0].transcript);setType(p.type);setAmount(String(p.amount||''));setCategory(p.category);setNote(p.note);setDate(p.date);setMessage('Áudio entendido. Confira os dados e salve.');};try{r.start()}catch{setMessage('Não foi possível iniciar o microfone.')}}
 function receipt(e){const f=e.target.files?.[0];if(!f)return;setOpen(true);setType('saida');setCategory('outros_s');setNote(`Comprovante: ${f.name}`);setMessage('Foto anexada. Nesta versão offline, confira e preencha valor/categoria manualmente. A leitura automática por IA exige um backend com chave privada.');e.target.value=''}
 function exportData(){const blob=new Blob([JSON.stringify(tx,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dcross-financeiro-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
 function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(Array.isArray(x)){setTx(x);setMessage('Backup importado com sucesso.')}}catch{alert('Arquivo de backup inválido.')}};r.readAsText(f);e.target.value=''}
 const cats=type==='entrada'?IN:OUT;
 return <div style={{background:C.bg,minHeight:'100vh',color:C.text,fontFamily:'system-ui,sans-serif',display:'flex',justifyContent:'center'}}><div style={{width:'100%',maxWidth:460,padding:'28px 20px 110px'}}>
 <header style={{display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{fontSize:13,color:C.muted,fontWeight:700}}>Assessor Financeiro D’Cross</div><div style={{fontSize:11,color:C.faint,marginTop:3}}>{new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</div></div><div style={{display:'flex',gap:6}}><button onClick={exportData} title="Exportar backup" style={iconBtn}><Download size={17}/></button><button onClick={()=>importRef.current?.click()} title="Importar backup" style={iconBtn}><Upload size={17}/></button></div></header>
 <input ref={importRef} type="file" accept="application/json" onChange={importData} hidden/><input ref={receiptRef} type="file" accept="image/*" capture="environment" onChange={receipt} hidden/>
 <section style={{padding:'28px 0 10px'}}><div style={{fontSize:13,color:C.muted}}>Saldo atual</div><div style={{fontFamily:'Georgia,serif',fontSize:40,fontWeight:600,color:data.saldo<0?C.red:C.text,marginTop:5}}>{brl(data.saldo)}</div></section>
 <div style={{display:'flex',gap:10,margin:'14px 0 22px'}}>{[[ArrowUpRight,'Entradas no mês',data.ins,C.gold],[ArrowDownRight,'Saídas no mês',data.outs,C.red]].map(([I,l,v,col])=><div key={l} style={{flex:1,background:C.surface,border:`1px solid ${C.border}`,borderRadius:14,padding:14}}><div style={{display:'flex',gap:6,alignItems:'center',color:col}}><I size={14}/><span style={{fontSize:11,color:C.muted}}>{l}</span></div><b style={{display:'block',fontSize:18,marginTop:7}}>{brl(v)}</b></div>)}</div>
 <div style={{display:'flex',alignItems:'center',gap:8,background:C.surface,border:`1px solid ${C.border}`,borderRadius:12,padding:'9px 12px',marginBottom:12}}><Search size={15} color={C.faint}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lançamento" style={{flex:1,background:'none',border:0,outline:0,color:C.text,fontSize:13}}/></div>
 <div style={{display:'flex',gap:8,marginBottom:18}}>{[['all','Tudo'],['in','Entradas'],['out','Saídas']].map(([k,l])=><button key={k} onClick={()=>setFilter(k)} style={{border:`1px solid ${filter===k?'transparent':C.border}`,background:filter===k?C.gold:'transparent',color:filter===k?C.bg:C.muted,borderRadius:20,padding:'7px 16px'}}>{l}</button>)}</div>
 {data.list.length===0?<div style={{border:`1px dashed ${C.border}`,borderRadius:16,padding:40,textAlign:'center',color:C.muted}}><BarChart3 size={24} style={{marginBottom:8}}/><div>Nenhum lançamento ainda.</div><span style={{fontSize:12}}>Toque no + para começar.</span></div>:data.list.map(t=>{const c=cat(t.category),I=c.icon,isIn=t.type==='entrada';return <div key={t.id} style={{display:'flex',alignItems:'center',gap:11,background:C.surface,border:`1px solid ${C.border}`,borderRadius:14,padding:12,marginBottom:7}}><div style={{width:36,height:36,borderRadius:10,display:'grid',placeItems:'center',background:C.alt,color:isIn?C.gold:C.red}}><I size={16}/></div><div style={{flex:1,minWidth:0}}><div style={{fontSize:13.5,fontWeight:600}}>{c.label}</div><div style={{fontSize:11,color:C.faint,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{t.note||new Date(t.date+'T00:00:00').toLocaleDateString('pt-BR')}</div></div><b style={{fontSize:13.5,color:isIn?C.gold:C.red}}>{isIn?'+':'−'} {brl(t.amount).replace('R$','').trim()}</b><button onClick={()=>setDel(t.id)} style={iconBtn}><Trash2 size={15}/></button></div>})}
 <div style={{position:'fixed',bottom:28,left:'50%',transform:'translateX(-50%)',display:'flex',gap:12,zIndex:10}}><button onClick={voice} style={{...smallBtn,background:listening?C.red:C.surface,color:listening?'#fff':C.gold}}><Mic size={20}/></button><button onClick={()=>receiptRef.current?.click()} style={smallBtn}><Camera size={20}/></button><button onClick={()=>{reset();setOpen(true)}} style={{...smallBtn,width:58,height:58,background:C.gold,color:C.bg,border:0}}><Plus size={27}/></button></div>
 {open&&<div onClick={()=>setOpen(false)} style={overlay}><div onClick={e=>e.stopPropagation()} style={sheet}><div style={{display:'flex',justifyContent:'space-between',marginBottom:18}}><b>Novo lançamento</b><button onClick={()=>setOpen(false)} style={iconBtn}><X size={20}/></button></div>{listening&&<div style={notice}>🎙️ Ouvindo… diga, por exemplo: “gastei 85 reais de Uber hoje”.</div>}{message&&<div style={notice}>{message}</div>}<div style={{display:'flex',gap:8,marginBottom:18}}>{[['entrada','Entrada'],['saida','Saída']].map(([k,l])=><button key={k} onClick={()=>{setType(k);setCategory(k==='entrada'?'cache':'equipamento')}} style={{flex:1,padding:11,borderRadius:12,border:`1px solid ${C.border}`,background:type===k?(k==='entrada'?C.gold:C.red):'transparent',color:type===k?C.bg:C.muted,fontWeight:700}}>{l}</button>)}</div><label style={label}>Valor</label><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="0,00" style={input}/><label style={label}>Categoria</label><div style={{display:'flex',flexWrap:'wrap',gap:8,marginBottom:16}}>{cats.map(c=><button key={c.key} onClick={()=>setCategory(c.key)} style={{border:`1px solid ${C.border}`,background:category===c.key?C.gold:'transparent',color:category===c.key?C.bg:C.muted,borderRadius:20,padding:'8px 12px'}}>{c.label}</button>)}</div><label style={label}>Descrição</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex: Santé Festival" style={input}/><label style={label}>Data</label><input type="date" value={date} onChange={e=>setDate(e.target.value)} style={{...input,colorScheme:'dark'}}/><button onClick={save} disabled={!(parseFloat(String(amount).replace(',','.'))>0)} style={{width:'100%',padding:15,borderRadius:14,border:0,background:C.gold,color:C.bg,fontWeight:800,opacity:parseFloat(String(amount).replace(',','.'))>0?1:.45}}>Salvar lançamento</button></div></div>}
 {del&&<div onClick={()=>setDel(null)} style={{...overlay,alignItems:'center',padding:24}}><div onClick={e=>e.stopPropagation()} style={{...sheet,borderRadius:18,maxWidth:320}}><b>Excluir lançamento?</b><p style={{fontSize:12.5,color:C.muted}}>Essa ação não pode ser desfeita.</p><div style={{display:'flex',gap:8}}><button onClick={()=>setDel(null)} style={{flex:1,padding:11,borderRadius:12,border:`1px solid ${C.border}`,background:'transparent',color:C.muted}}>Cancelar</button><button onClick={()=>{setTx(tx.filter(t=>t.id!==del));setDel(null)}} style={{flex:1,padding:11,borderRadius:12,border:0,background:C.red,color:'#fff'}}>Excluir</button></div></div></div>}
 </div></div>}
const smallBtn={width:50,height:50,borderRadius:999,background:C.surface,border:`1px solid ${C.border}`,color:C.gold,display:'grid',placeItems:'center',boxShadow:'0 6px 18px rgba(0,0,0,.35)'};
const overlay={position:'fixed',inset:0,background:'rgba(0,0,0,.6)',display:'flex',alignItems:'flex-end',justifyContent:'center',zIndex:20};
const sheet={width:'100%',maxWidth:460,background:C.surface,border:`1px solid ${C.border}`,borderBottom:0,borderTopLeftRadius:24,borderTopRightRadius:24,padding:'20px 20px 28px',maxHeight:'90vh',overflowY:'auto'};
const iconBtn={background:'none',border:0,color:C.muted,padding:5};
const label={display:'block',fontSize:11.5,color:C.muted,marginBottom:6,fontWeight:600};
const input={width:'100%',background:C.alt,border:`1px solid ${C.border}`,borderRadius:12,padding:'12px 14px',color:C.text,fontSize:14,outline:'none',marginBottom:16};
const notice={padding:12,borderRadius:12,background:'rgba(201,162,75,.12)',color:C.gold,fontSize:12,lineHeight:1.45,marginBottom:14};
